### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by winkler1** [Cmdv/essential-tdd-bdd-react-list#2]
Hi-
 Not sure how you're organizing this, so I'll put some things here--

Did a quick (3:45) screencast of #reactjs react-bootstrap's test suite running with Karma. 229 tests, sub-second. http://screencast.com/t/4huigNm9oc -- https://twitter.com/winkler1/status/540226940998025216

^^^ IMO, Karma+ReactTestUtils is the way to go. Fast feedback loops!

On the other hand, I've seen lots of feedback that Jest was slow. 100X slower than Karma/Mocha/Chai. Example - https://medium.com/about-codecademy/testing-with-reactjs-at-codecademy-2aec88cc4e36. Another: http://www.hammerlab.org/2015/02/14/testing-react-web-apps-with-mocha/

Automated testing in Yahoo: http://yahooeng.tumblr.com/post/115664629471/automated-testing-in-yahoo-mail … Mocha, Chai, Karma, Protractor, Sinon.. all the way to smoke+intgrtn tests #tdd #reactjs

More Karma/Webpack setups
- http://qiita.com/kimagure/items/f2d8d53504e922fe3c5c
- http://dapperdeveloper.com/2015/05/11/testing-a-react-project-with-karma-and-webpack/

**Comment by Cmdv** [comment]
Hi, 

grand I'll add them in thank you, much prefer learning from videos so hopefully we'll get more. I might do a section / other readme on preferred setup / speed specs so I'll add that info there.

**Comment by Cmdv** [comment]
They've been added, kept it to one page in the end. Thanks for the contribution.
